tax-fee-data:
  byCity:
    gothenburg:
      - fromTime: "06:00:00"
        toTime: "06:29:00"
        fee: 8
      - fromTime: "06:30:00"
        toTime: "06:59:00"
        fee: 13
      - fromTime: "07:00:00"
        toTime: "07:59:00"
        fee: 18
      - fromTime: "08:00:00"
        toTime: "08:29:00"
        fee: 13
      - fromTime: "08:29:00"
        toTime: "14:59:00"
        fee: 8
      - fromTime: "15:00:00"
        toTime: "15:29:00"
        fee: 13
      - fromTime: "15:30:00"
        toTime: "16:59:00"
        fee: 18
      - fromTime: "17:00:00"
        toTime: "17:59:00"
        fee: 13
      - fromTime: "18:00:00"
        toTime: "18:29:00"
        fee: 8